apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    annotations:
        metallb.universe.tf/allow-shared-ip: sharing_key
spec:
    ports:
        - port: 80
          name: http
          nodePort: 80
        - port: 443
          name: https
          nodePort: 443
    selector:
        app: nginx
    type: LoadBalancer
    loadBalancerIP: 172.17.0.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            hostname: nginx
            containers:
                - name: nginx
                  image: nginx-svc
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 80
                  - containerPort: 443
                  