apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing_key
  labels:
    app: wp
spec:
  selector:
    app: wp-pod
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  ports:
  - port: 5050
    name: wp-port
    targetPort: wp-container
    protocol: TCP
    nodePort: 5050

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wp-deploy
spec:
  selector:
    matchLabels:
      app: wp-pod
  template:
    metadata:
      labels:
        app: wp-pod
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wp-container
